version: "3.7"
services:
  Postgres:
    image: postgres
    restart: always
    ports:
      - 5436:5432
    env_file:
      - .env
  Adminer:
    image: adminer
    restart: always
    links:
      - Postgres:postgres
    ports:
      - 4444:8080
  mys3bucket:
    build: .
    ports:
      - 8080:8080
    links:
      - Postgres:postgres
    env_file:
      - .env
