name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: ibrahima
          POSTGRES_PASSWORD: ibrahima
          POSTGRES_HOST: localhost
          POSTGRES_DB: myS3
          POSTGRES_PORT: 5432
          POSTGRES_TEST_USER: ibrahima
          POSTGRES_TEST_PASSWORD: ibrahima
          POSTGRES_TEST_HOST: localhost
          POSTGRES_TEST_DB: myS3Test
          POSTGRES_TEST_PORT: 5432
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and test
        run: |
          yarn
          yarn test
        env:
          CI: true
          APP_PORT: 8080
          jwtSecret: Br@ms
          BDD_type: postgres
          POSTGRES_USER: ibrahima
          POSTGRES_PASSWORD: ibrahima
          POSTGRES_HOST: localhost
          POSTGRES_DB: myS3
          POSTGRES_PORT: 5432
          POSTGRES_TEST_USER: ibrahima
          POSTGRES_TEST_PASSWORD: ibrahima
          POSTGRES_TEST_HOST: localhost
          POSTGRES_TEST_DB: myS3Test
          POSTGRES_TEST_PORT: 5432
          GMAIL_USER: mys3bucket@gmail.com
          GMAIL_PASSWORD: NiCalBon2019
